/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.ui;

import org.example.file.FileUtil;
import org.example.file.FormatHandler;
import org.example.controller.AppController;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Damon Morgan, Ernesto Felix
 */
public class EditWindow extends javax.swing.JFrame {
    private String filePath;
    private AppController appController;

    /**
     * Creates new form InstructionWindow
     */
    public EditWindow(AppController appController) {
        this.appController = appController;
        filePath = "instructions.txt";
        initComponents();
        addPopupMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        doneButton = new javax.swing.JButton();
        saveChangesCheckBox = new javax.swing.JCheckBox();
        saveAsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        scrollToTopButton = new javax.swing.JButton();
        formatConvertCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        saveChangesCheckBox.setText("Save changes");
        saveChangesCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesCheckBoxActionPerformed(evt);
            }
        });

        saveAsButton.setText("Save As");
        saveAsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel1.setText("View and edit");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Max instructions: 250");

        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Instructions exceeding 250 will be removed");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scrollToTopButton.setText("Scroll to top");
        scrollToTopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scrollToTopButtonActionPerformed(evt);
            }
        });

        formatConvertCheckBox.setText("Convert to 6 digit instruction format");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(374, 374, 374)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(saveChangesCheckBox)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(saveAsButton))
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(formatConvertCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doneButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollToTopButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollToTopButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(saveChangesCheckBox)
                                    .addComponent(saveAsButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(formatConvertCheckBox)
                                .addGap(6, 6, 6)))
                        .addComponent(jLabel3))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        // TODO add your handling code here:
        List<Integer> instructions = extractInstructionsFromTextAreaInt();

        if(formatConvertCheckBox.isSelected()){
            instructions = FormatHandler.convertInstructionsToNewFormat(instructions);
            for (Integer instruction : instructions) {
                int operation = instruction / 1000;
                int operand = instruction % 100;
                System.out.println("newInstruction: " + instruction);
                System.out.println("operation: " + operation);
                System.out.println("operand: " + operand);
            }
        }

        if(saveChangesCheckBox.isSelected()) {
            appController.getMemoryManager().writeToMemoryFromIntegerList(instructions);
            appController.getFileManager().saveInstructionsToFileFromMemory(filePath);
        }else{
            List<Integer> list = FileUtil.readFileAsIntegerList(new File(filePath));
            appController.getMemoryManager().writeToMemoryFromIntegerList(list);
            appController.getFileManager().saveInstructionsToFileFromMemory(filePath);
        }
        dispose();
    }//GEN-LAST:event_doneButtonActionPerformed

    private void saveChangesCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveChangesCheckBoxActionPerformed

    private void scrollToTopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scrollToTopButtonActionPerformed
        // TODO add your handling code here:
        jScrollPane1.getVerticalScrollBar().setValue(0);
    }//GEN-LAST:event_scrollToTopButtonActionPerformed

    private void saveAsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsButtonActionPerformed
        // TODO add your handling code here:
        List<String> instructions = extractInstructionsFromTextArea();

        appController.getMemoryManager().writeToMemoryFromStringList(instructions);
        appController.getFileManager().saveAsInstructionsToFileFromMemory();

    }//GEN-LAST:event_saveAsButtonActionPerformed

    /**
     * Creates and shows the instruction window with the given file path and instructions.
     *
     * @param path the file path of the program
     * @param instructions the list of instructions
     */
    public void createAndShowEditWindow(String path, List<String> instructions) {
        setVisible(true);
        setFilePath(path);
        appendInstructions(instructions);
    }

    /**
     * Appends a list of instructions to the text area.
     *
     * @param instructions the list of instructions to append
     */
    public void appendInstructions(List<String> instructions) {
        for (int j = 0; j < 100 && j < instructions.size(); j++) {
            String instruction = instructions.get(j);
            textArea.append(instruction + "\n");
        }
    }

    /**
     * Sets the file path for saving instructions.
     *
     * @param filePath the file path
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    /**
     * Retrieves text from the text area.
     *
     * @return the list of instructions
     */
    private List<String> extractInstructionsFromTextArea() {
        List<String > instructions = new ArrayList<>();

        String text = textArea.getText();

        String[] lines = text.split("\\n");

        int i = 0;
        for (String line : lines) {
            instructions.add(line);
            System.out.println("line: " + i + ": " + line);
            i++;
        }
        return instructions;
    }

    private List<Integer> extractInstructionsFromTextAreaInt() {
        List<Integer> instructions = new ArrayList<>();

        String text = textArea.getText();

        String[] lines = text.split("\\n");

        int i = 0;
        for (String line : lines) {
            instructions.add(Integer.parseInt(line));
            System.out.println("line: " + i + ": " + line);
            i++;
        }
        return instructions;
    }

    /**
     * By Ernesto Felix
     * Adds a popup menu with Cut, Copy, and Paste functionality to the text area.
     */
    private void addPopupMenu() {
        JPopupMenu popupMenu = new JPopupMenu();

        JMenuItem cutMenuItem = new JMenuItem("Cut");
        cutMenuItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                textArea.cut();
            }
        });
        popupMenu.add(cutMenuItem);

        JMenuItem copyMenuItem = new JMenuItem("Copy");
        copyMenuItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                textArea.copy();
            }
        });
        popupMenu.add(copyMenuItem);

        JMenuItem pasteMenuItem = new JMenuItem("Paste");
        pasteMenuItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                textArea.paste();
            }
        });
        popupMenu.add(pasteMenuItem);

        textArea.setComponentPopupMenu(popupMenu);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doneButton;
    private javax.swing.JCheckBox formatConvertCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveAsButton;
    private javax.swing.JCheckBox saveChangesCheckBox;
    private javax.swing.JButton scrollToTopButton;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
